### ISSUE TITLE
uses of Math.pow(x, 2)

### ISSUE THREAD

**Issue by davidrapin** [sheymann/primitives2d#1]
always prefer `x*x` to `Math.pow(x, 2)` as Math.pow is known to be much slower.
http://stackoverflow.com/questions/936541/math-pow-vs-multiply-operator-performance

**Comment by sheymann** [comment]
Performances vary depending on the browser. Using https://jsperf.com/math-pow-vs-simple-multiplication/ I get:
- 2% improvements using `x*x` on Chrome
- no significant change on Firefox
- 96% improvement on IE11 and 70% using a function
